apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: monitoring
  labels:
    app: microservice
    team: s8ul
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 1m
    route:
      group_by: [alertname, pod]
      receiver: discord-default
    receivers:
    - name: discord-default
      webhook_configs:
      - url: https://discord.com/api/webhooks/REPLACE_WITH_DEFAULT_WEBHOOK
