FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app.py .
COPY shared_app.py .
ENV POD_NAME=local NAMESPACE=kubeguard VERSION=2.0.0 SERVICE_NAME=worker-service
EXPOSE 8002
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8002"]
